services:
  - type: web
    name: devis-btp-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: WEAVIATE_URL
        value: $WEAVIATE_URL
      - key: WEAVIATE_API_KEY
        value: $WEAVIATE_API_KEY
